environment:
  npm_version: latest
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 10

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - git submodule update --init --recursive
  - npm --version
  - npm install -g npm@%npm_version%
  - npm --version
  - node --version
  - npm install

test_script:
  - npm test

build: off
